Name:           ros-kinetic-schunk-sdh
Version:        0.6.9
Release:        0%{?dist}
Summary:        ROS schunk_sdh package

Group:          Development/Libraries
License:        LGPL
URL:            http://ros.org/wiki/schunk_sdh
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       dpkg
Requires:       libusb-devel
Requires:       ros-kinetic-actionlib
Requires:       ros-kinetic-cob-srvs
Requires:       ros-kinetic-control-msgs
Requires:       ros-kinetic-diagnostic-msgs
Requires:       ros-kinetic-libntcan
Requires:       ros-kinetic-libpcan
Requires:       ros-kinetic-message-runtime
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-sensor-msgs
Requires:       ros-kinetic-std-msgs
Requires:       ros-kinetic-std-srvs
Requires:       ros-kinetic-trajectory-msgs
Requires:       ros-kinetic-urdf
BuildRequires:  boost-devel
BuildRequires:  dpkg
BuildRequires:  libusb-devel
BuildRequires:  ros-kinetic-actionlib
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-cob-srvs
BuildRequires:  ros-kinetic-control-msgs
BuildRequires:  ros-kinetic-diagnostic-msgs
BuildRequires:  ros-kinetic-libntcan
BuildRequires:  ros-kinetic-libpcan
BuildRequires:  ros-kinetic-message-generation
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-roslint
BuildRequires:  ros-kinetic-sensor-msgs
BuildRequires:  ros-kinetic-std-msgs
BuildRequires:  ros-kinetic-std-srvs
BuildRequires:  ros-kinetic-trajectory-msgs
BuildRequires:  ros-kinetic-urdf

%description
This package provides an interface for operating the schunk dexterous hand
(SDH), including the tactile sensors.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed Jul 19 2017 Mathias Luedtke <mdl@ipa.fhg.de> - 0.6.9-0
- Autogenerated by Bloom

